config/routes.rb
Rails.application.routes.draw do
  resources :charts do
    member do
      put 'versionalize'
      put 'share'
    end
    resources :chart_versions
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'home#land'

end

app/models/chart.rb
# == Schema Information
#
# Table name: charts
#
#  id                     :integer          not null, primary key
#  title                  :string
#  description            :text
#  customer_segments      :text
#  value_propositions     :text
#  customer_relationships :text
#  channels               :text
#  key_activities         :text
#  key_resources          :text
#  key_partnerships       :text
#  cost_structure         :text
#  revenue_streams        :text
#  owner_id               :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Chart < ActiveRecord::Base
  attr_accessor :invite_emails

  belongs_to :owner, class_name: User.name
  has_many :versions, class_name: ChartVersion.name, dependent: :destroy
  has_many :chart_subscriptions
  has_many :users, through: :chart_subscriptions

  validates :title, presence: true
  validates :owner, presence: true

  after_create :subscribe_owner

  def versionalize!
    self.versions.create!
  end

  def share_with(usr)
    ChartSubscription.find_or_create_by(user_id: usr.id, chart_id: self.id)    
  end

private
  def subscribe_owner
    self.share_with(self.owner)
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_chart, only: [:show, :update, :destroy, :versionalize, :share]

  def index
    @charts = current_user.charts.all
    @new_chart = current_user.charts.new
  end

  def create
    @chart = current_user.authored_charts.new(chart_params)
    if @chart.save
      redirect_to chart_path(@chart)
    else
      redirect_to root_path, alert: "#{@chart.errors.full_messages.join(", ")}. Please try again"
    end
  end

  def show
    if params[:v]
      @chart_version = @chart.versions.where(counter: params[:v].to_i).first
    end
  end

  def update
    @chart.update_attributes(chart_update_params)

    respond_to do |format|
      format.js { render 'update' }
      format.json { respond_with_bip(@chart) }
    end
  end

  def share
    emails = params[:chart][:invite_emails]
    emails.gsub!(" ", "")
    emails = emails.split(",")
    ignored_emails = []
    emails.reject!(&:blank?)
    emails.uniq!
    emails.each do |email|
      usr = User.find_by(email: email)
      if usr
        @chart.share_with(usr)
      else
        ignored_emails.push(email)
      end
    end

    if ignored_emails.any?
      redirect_to chart_path(@chart), alert: "The following emails are not associated with any user; Hence, not share with them: #{ignored_emails.join(', ')}."
    else
      redirect_to chart_path(@chart), notice: "Successfully shared with #{emails.count} users."
    end
  end

  def destroy
    @chart.destroy
    redirect_to root_path, notice: "#{@chart.title} deleted successfully."
  end

  def versionalize
    @chart.versionalize!

    redirect_to chart_path(@chart, v: @chart.versions.last.counter)
  end

private
  def chart_params
    params.require(:chart).permit(:title, :description)
  end

  def chart_update_params
    params.require(:chart).permit(
      :title,
      :description,
      :customer_segments, 
      :value_propositions, 
      :customer_relationships, 
      :channels, 
      :key_activities, 
      :key_resources, 
      :key_partnerships, 
      :cost_structure, 
      :revenue_streams
    )
  end

  def fetch_chart
    @chart = current_user.charts.find(params[:id])
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
  def chart_cell_content(chart, chart_version, col_name)
    content_tag(:h4, col_name.to_s.titleize) +
      content_tag(:div, class: "content") do
        raw (chart_version || chart).send(col_name)
      end +
      (chart_version ? "" : link_to(fa_icon("pencil"), "#", class: "modal-trigger", data: {toggle: "modal", target: "##{col_name.to_s}-modal"}))
  end
end

app/views/charts/_chart.html.erb
<% show_link_id = "show-chart-link-#{chart.id}" %>
<div class="flip-container chart-slide" data-target="#<%= show_link_id %>">
  <div class="flipper">
    <% chart_cycle_class = "chart-#{cycle(1, 2, 3, 4, 5, 6)}" %>
    <article class='front chart <%= chart_cycle_class %>'>
      <div class="vcenter">
        <%= chart.title %>
      </div>
    </article>
    <article class='back chart <%= chart_cycle_class %>'>
      <div class="vcenter">
        <h3><%= chart.title %></h3>
        <p><%= chart.description %></p>
      </div>
    </article>
  </div>
</div>
<%= link_to "View", chart_path(chart), id: show_link_id, class: "hidden" %>

app/views/charts/_edit_modals.html.erb
<% [:customer_segments, 
      :value_propositions, 
      :customer_relationships, 
      :channels, 
      :key_activities, 
      :key_resources, 
      :key_partnerships, 
      :cost_structure, 
      :revenue_streams].each do |col_name| %>
  <div class="modal fade canvas-modal" id="<%= col_name.to_s %>-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><%= fa_icon "times-circle" %></span></button>
          <h4 class="modal-title"><%= col_name.to_s.titleize %></h4>
        </div>
        <div class="modal-body">
          <p>Describe your <%= col_name.to_s.titleize %>:</p>
          <%= simple_form_for @chart, remote: true do |f| %>
            <%= f.input col_name, label: false, :as => :ckeditor %>
            <%= f.submit "Save", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/charts/_form.html.erb
<%= simple_form_for @new_chart do |f| %>
  <%= f.input :title, label: false, placeholder: "Title of the Business Idea" %>
  <%= f.input :description, label: false, placeholder: "Describe the idea" %>
  <%= f.submit "Create", class: "btn", data: {'disable-with' => "Please Wait"} %>
  <%= link_to "cancel", "#", class: "cancel" %>
<% end %>

app/views/charts/_version_navigation.html.erb
<div id="version_navigation" class="pull-right">
  <% if !@chart_version && !@chart.versions.any? %>
    <%# Viewing a live version of chart, which doesn't have any versions' %>
    <%= link_to fa_icon("plus-circle", text: "Create Version"), versionalize_chart_path(@chart), method: :put, class: "btn btn-primary" %>
  <% else %>
    <div class="btn-group">
      <% if @chart_version %>
        <button type="button" class="btn btn-primary">
          <%= @chart_version.title_for_display %>
        </button>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
      <% else %>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Choose Version <span class="caret"></span>
        </button>
      <% end %>
      <ul class="dropdown-menu">
        <li>
          <% if @chart_version %>
            <%= link_to "Live", chart_path(@chart) %>
          <% else %>
            <%= link_to fa_icon("plus-circle", text: "Create Version"), versionalize_chart_path(@chart), method: :put %>
          <% end %>
        </li>
        <li role="separator" class="divider"></li>
        <% @chart.versions.reverse.each do |chart_version| %>
          <li>
            <%= link_to "V#{chart_version.counter} - #{chart_version.created_at.strftime('%b %e, %Y')}", chart_path(@chart, v: chart_version.counter) %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= fa_icon "cog" %>
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
      <li>
          <%= link_to fa_icon("share", text: "Share"), "#", id: "share-link-trigger" %>
      </li>
      <li>
        <% if @chart_version %>
          <%= link_to fa_icon("trash", text: "Delete #{@chart_version.title_for_display}"), chart_chart_version_path(@chart, @chart_version), method: :delete, data: {confirm: "#{@chart_version.title_for_display} of #{@chart.title} will be deleted. The titles of other versions of #{@chart.title} will be modified to preserve the ordering.\nAre you sure you want to delete #{@chart_version.title_for_display}?"} %>
        <% else %>
          <%= link_to fa_icon("trash", text: "Delete Chart"), chart_path(@chart), method: :delete, data:{confirm: 
            "The business model and all it's versions will be deleted. This is irreversible.\nAre you sure you want to delete the business model?"} %>
        <% end %>        
      </li>
    </ul>
  </div>
</div>

<div id="share-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Share Model</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @chart, url: share_chart_path(@chart), method: :put do |f| %>
          <p>
            Current shared with:
            <ul>
              <% @chart.users.each do |user| %>
                <li><%= user.name %></li>
              <% end %>
            </ul>
          </p>
          <p>Please enter comma separated list of emails to share with.</p>
          <%= f.input :invite_emails, as: :text, label: false %>
          <%= f.submit "Share", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/charts/index.html.erb
<section id="charts" data-no-turbolink>
  <h1>My Business Models</h1>
  <div class="">
    <div class="flip-container new_chart_container">
      <div class="flipper">
        <article class="front chart new_chart">
          <div class="vcenter">
            <%= fa_icon "plus-circle", text: "Add New Model" %>
          </div>
        </article>
        <article class='back chart new_chart'>
          <div class="vcenter">
            <h2>Add a New Model</h2>
            <%= render 'charts/form' %>
          </div>
        </article>
      </div>
    </div>
    <%= render @charts %>
  </div>
</section>

app/views/charts/show.html.erb
<div id="chart" class="container-fluid" data-no-turbolink>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <%= render "charts/version_navigation" %>
      <h1 id="title">
        <% if @chart_version %>
          <%= @chart_version.title %>
          <div class="version_details">
            (<%= @chart_version.title_for_display %> - READ ONLY)
          </div>
        <% else %>
          <%= fa_icon "pencil", class: "edit_indicator" %>
          <%= best_in_place @chart, :title %>
        <% end %>
      </h1>
      <p id="description">
        <% if @chart_version %>
          <%= @chart_version.description %>
        <% else %>
          <%= fa_icon "pencil", class: "edit_indicator" %>
          <%= best_in_place @chart, :description, as: :textarea %>
        <% end %>
      </p>
    </div>
    <div class="col-xs-1"></div>
  </div>

  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-2 canvas-box" id="key_partnerships">
      <%= chart_cell_content(@chart, @chart_version, :key_partnerships) %>
    </div>
    <div class="col-xs-2">
      <div id="key_activities" class="canvas-box">
        <%= chart_cell_content(@chart, @chart_version, :key_activities) %>
      </div>
      <div id="key_resources" class="canvas-box">
        <%= chart_cell_content(@chart, @chart_version, :key_resources) %>
      </div>
    </div>
    <div class="col-xs-2 canvas-box" id="value_propositions">
      <%= chart_cell_content(@chart, @chart_version, :value_propositions) %>
    </div>
    <div class="col-xs-2">
      <div id="customer_relationships" class="canvas-box">
        <%= chart_cell_content(@chart, @chart_version, :customer_relationships) %>
      </div>
      <div id="channels" class="canvas-box">
        <%= chart_cell_content(@chart, @chart_version, :channels) %>
      </div>
    </div>
    <div class="col-xs-2 canvas-box" id="customer_segments">
      <%= chart_cell_content(@chart, @chart_version, :customer_segments) %>
    </div>
    <div class="col-xs-1"></div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-5 canvas-box" id="cost_structure">
      <%= chart_cell_content(@chart, @chart_version, :cost_structure) %>
    </div>
    <div class="col-xs-5 canvas-box" id="revenue_streams">
      <%= chart_cell_content(@chart, @chart_version, :revenue_streams) %>
    </div>
    <div class="col-xs-1"></div>
  </div>

  <%= render "charts/edit_modals" unless @chart_version %>
</div>

app/views/charts/update.js.erb
<% col_name = params[:chart].keys.first %>
$('.modal').modal('hide');
$('#<%= col_name %> .content').html('<%= j raw(@chart.send(col_name)) %>');